### PR TITLE
Refix Date on Windows

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
So it's going to fail because of gdk but the date part is legit now.

**Comment by gkoz** [comment]
@GuillaumeGomez Yesterday's half-finished PRs notwithstanding I believe I've earned the push access to all of the repos :p

**Comment by GuillaumeGomez** [comment]
@gkoz: You already have it, no ?

**Comment by gkoz** [comment]
Only the sys repo.

**Comment by GuillaumeGomez** [comment]
Seriously ?! I thought this right was for all. I change it.

**Comment by GuillaumeGomez** [comment]
Ok, it should good now.

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
