### PR TITLE
Update license headers and authors list

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
It might seem a bit stupid but why `rust-GNOME` instead of `rust-gnome` ?

**Comment by gkoz** [comment]
GNOME is their official project name and all lowercase seemed ugly in its own way...

**Comment by gkoz** [comment]
We're capitalizing all the words in these cases ("The ... Project Developers") to make it look super important :). In a usual text it might just be 'rust-gnome'.

**Comment by GuillaumeGomez** [comment]
I don't have any preference on that so let's say we'll keep it that way. Thanks for the "making it look super important" ! ;-)

**Pull request merged**
