### PR TITLE
Remove redundant dependency

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
That's weird. I thought we add to give the c_vec link...

**Comment by gkoz** [comment]
Only `gdk` and `cairo` use `CVec` right now.

**Comment by GuillaumeGomez** [comment]
I never paid attention... Thanks anyway.

**Comment by gkoz** [comment]
FYI the other repos fill fail the tests until this is merged.

**Comment by GuillaumeGomez** [comment]
I'll restart the tests.

**Pull request merged**
