### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'm gonna split out pango this evening. We should also change headers of files (that's a lot of code...). Thanks for that !

**Comment by gkoz** [comment]
The headers, right :)
But they shouldn't take a lot of work. Hopefully we can automate the process.

**Comment by GuillaumeGomez** [comment]
Yep, but it remains annoying ^^'

**Comment by gkoz** [comment]
As we're breaking everything anyway, this seems to be a good occasion to follow Rust's style and make feature flags lowercase.

**Comment by GuillaumeGomez** [comment]
I agree !

**Pull request merged**
