### PR TITLE
Manually bind Binding::unbind()

### PR DESCRIPTION
**Pull request by sdroege**
It is wrongly marked as transfer-none

### CODE REVIEW

**Comment by EPashkin** [comment]
Code looks good, but maybe better fix .gir file and change this PR to only remove trait generation?

**Comment by sdroege** [comment]
I thought we generally prefer to only edit gir files if it can't be easily solved otherwise

**Comment by EPashkin** [comment]
IMHO it was before we get normal script for update gir files.
Now we have stable way to reapply changes.

**Comment by sdroege** [comment]
@GuillaumeGomez What do you prefer?

**Comment by GuillaumeGomez** [comment]
I have a preference to @EPashkin's proposition.

**Comment by sdroege** [comment]
Ok, I don't know how to use this thing. How would this look correct?
```
xmlstarlet ed -P -L \
                                        -u '//_:class[@name="Binding"]/_:method[@name="unbind"]//_:instance-parameter[@name="binding"]/@transfer' -v "full" \
                                        GObject-2.0.gir
```

**Comment by EPashkin** [comment]
Typo: "/@transfer-ownership" instead just "transfer"

**Comment by sdroege** [comment]
Ah

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gir-files/pull/24  and after that is merged I'll update this one here

**Comment by GuillaumeGomez** [comment]
The other PR has been merged. :)

**Comment by EPashkin** [comment]
Looks good, but maybe better combine "Regenerate with latest gir-files" with "Don't generate a trait for Binding", or combine all 3 commits as "Don't generate a trait for Binding"

**Comment by sdroege** [comment]
Which of the two options you gave? Those two options and the three commits make no difference to me :)

**Comment by EPashkin** [comment]
Personally I don't like last commit with one line change,
and prefer one commit option as it clear states what it do.

**Comment by sdroege** [comment]
Ok, for that @GuillaumeGomez can simply click on the "rebase & squash" button when he merges. That's most easy

**Comment by GuillaumeGomez** [comment]
I didn't know I could. If you're fine with this then I'll click on "the" button. :p

**Comment by EPashkin** [comment]
@sdroege You forgot to add right `versions.txt`

**Comment by sdroege** [comment]
Indeed, I add that later when I'm back at the computer

**Comment by sdroege** [comment]
Now with correct versions.txt :)

**Comment by GuillaumeGomez** [comment]
Thanks! (just waiting for CIs and then I merge)

**Comment by sdroege** [comment]
All green :)

**Comment by GuillaumeGomez** [comment]
Then I merge!

**Pull request merged**
