### PR TITLE
Fix the 32-bit build by truncating the microseconds value

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
The truncation may easily cause bugs though...

**Comment by GuillaumeGomez** [comment]
Hum... Yes it could since it's supposed to be 64 bits...

**Comment by gkoz** [comment]
I think we don't need `g_usleep` at all and the add method could be implemented in Rust (BTW its argument should've been signed).

**Comment by gkoz** [comment]
Another option is to implement `from/to_glib` for `TimeVal` <-> `Duration`.

**Pull request merged**
